name: CI/CD for ChatBot Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Backend CI
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Backend Tests
        run: |
          cd backend
          pytest

  # Frontend CI
  frontend-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Linting Tools
        run: |
          npm install -g htmlhint csslint eslint

      - name: Lint HTML
        run: htmlhint frontend/index.html

      - name: Lint CSS
        run: csslint frontend/styles.css

      - name: Lint JavaScript
        run: eslint frontend/script.js

  # Deployment to EC2
  deploy:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-linting]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          ssh -i "${{ secrets.EC2_KEY }}" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /path/to/project
          git pull origin main
          cd backend
          nohup python app.py &
          EOF
